const express = require('express');
const router = express.Router();
const { createJobAlert, getJobAlerts, updateJobAlert, deleteJobAlert,getJobAlertById } = require('../controllers/jobAlertControllers');
const { authMiddleware, authorize } = require('../middleware/auth');
router.post('/', authMiddleware, authorize(['JobSeeker', 'Admin']), createJobAlert);
router.get('/', authMiddleware, authorize(['JobSeeker', 'Admin']), getJobAlerts);
router.get('/:id', authMiddleware, authorize(['JobSeeker', 'Admin']), getJobAlertById);
router.patch('/:id', authMiddleware, authorize(['JobSeeker', 'Admin']), updateJobAlert);
router.delete('/:id', authMiddleware, authorize(['JobSeeker', 'Admin']), deleteJobAlert);
module.exports = router;